### ISSUE TITLE
Resource Index shows up in the UI Tools drop down menu

### ISSUE THREAD

**Issue by alexskr** [ncbo/virtual_appliance#1]
Resource Index is not bundled in with the appliance and we have previously disabled it by setting RESOURCE_INDEX_DISABLED config setting to true in previous versions of the appliance.  
recent UI redesign doesn't take that into consideration so Resource Index link shows up in the Tools menu

**Comment by jvendetti** [comment]
Fixed in this commit: https://github.com/ncbo/bioportal_web_ui/commit/265d310093660e81b0aacbe26ffe506932dfe6ab#diff-cbde8caf34a9df6846ea150226013b85.
