### ISSUE TITLE
Virtual Appliance 3.0.5 shows wrong version (3.0.4) in Portal

### ISSUE THREAD

**Issue by dalito** [ncbo/virtual_appliance#25]
The appliance version is set at two places but only one was updated before releasing/tagging 3.0.5.

Missed:
https://github.com/ncbo/virtual_appliance/blob/32cd9c3f16e5dff91726722a070fdd1600449bcb/appliance_config/bioportal_web_ui/config/bioportal_config_appliance.rb.default#L65

The other place which was updated is: ` virtual_appliance/deployment/versions`

**Comment by alexskr** [comment]
Thanks!  We will fix it in the next release.

**Comment by alexskr** [comment]
fixed in v3.0.6
