### ISSUE TITLE
Appliance 3.0.6.ova failing to start in Virtual Box on Windows 10 

### ISSUE THREAD

**Issue by jvendetti** [ncbo/virtual_appliance#29]
Report from end user on the support list:

> I am currently using 3.0.5-ova. Today, I tried to set up 3.0.6 ova
> Importing the appliance to Virtual Box 6.1.30 on Win10Pro-64bit was possible. However, starting the appliance failed with lots of warning lines:
 > ```dracut-initqueue[234]: Warning: dracut-initqueue timeout - starting timeout scripts```
> ending with a line 
> ```Entering emergency mode```.
> Finally a `dracut:/#` prompt is shown.
> The md5-hash of the downloaded appliance was AF033F46E2DD9D577B5788E66C689427

I downloaded 3.0.6.ova and tested on my local machine. I was able to launch w/out issue using VMWare Fusion Professional Version 12.0.0. I'm running macOS Monterey v12.2. Issue appears to be specific to certain environments.

**Comment by dalito** [comment]
@jvendetti - Thanks for converting my support request to a github issue. If there are any questions on details I can answer them here.

**Comment by alexskr** [comment]
VirtualBox compatibility is restored in v3.1.0 of the appliance
